name: XSS

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-XSS
    ports:
      - "5436:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: fraud
      POSTGRES_DB: fraud
      POSTGRES_USER: fraud
